# .github/workflows/terraform-cicd.yml

name: Terraform CI/CD

on:
  push:
    branches:
      - main  # Or your desired deployment branch
    paths:
      - 'terraform/**'  # Trigger only on changes to the Terraform folder
      - '.github/workflows/terraform_CICD.yml'

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    environment: production  # Or the environment you want to deploy to (e.g., staging)

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.1  # Specify the Terraform version (e.g., 1.3.0)

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform Init
        working-directory: terraform  # Navigate to the Terraform folder
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan
        continue-on-error: true # If you want to continue even if the plan fails (for logging purposes)

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve

      - name: Install EBS CSI Driver
        working-directory: terraform
        run: |
          aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name ${{ secrets.CLUSTER_NAME }}
          kubectl apply -k "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=release-1.31"
          kubectl apply -f ../k8s-manifests/database.yaml
          kubectl apply -f ../k8s-manifests/secret.yaml
          kubectl apply -f ../k8s-manifests/service.yaml
